import { Component } from '@angular/core';

function log(target, name, descriptor) {
  console.log(target, name, descriptor);
  // Store the original function in a variable
  const original = descriptor.value
  // Do some manipulations in the descriptor.value which is the function
  // original()
  // descriptor.value = function() {
  //   console.log("Hi Michael, Kudos!!!"); 
  // }

  descriptor.value = function(...args) {
    console.log("Arguments ", args, " were passed in this function")
    const result = original.apply(this, args)
    console.log("The result of the function is ", result);
    return result 
  }

  // Return the descriptor
  return descriptor
}

@Component({ 
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro2angular';

  constructor() {
    console.log('This statement was generated by the constructor', this.aSimpleMethod(5, 2));   
  }

  @log aSimpleMethod(m, n) {
    // console.log("Hi Nicholas, I'm learning Angular!");
    return m*n
  }
}
